---
- hosts: all
  vars:
    golang: 1.25.7
    srcurl: https://go.dev/dl/
  tasks:
  - name: "fetch golang x86 tarball"
    get_url:
        url: "{{ srcurl }}/go{{ golang }}.linux-amd64.tar.gz"
        dest: "/var/tmp/go{{ golang }}.linux-amd64.tar.gz"
  - name: "create golang install dir"
    file:
        path: /usr/local/go-{{ golang }}
        state: directory
  - name: "unpack golang x86 tarball"
    unarchive:
        src: "/var/tmp/go{{ golang }}.linux-amd64.tar.gz"
        dest: /usr/local/go-{{ golang }}
        extra_opts: [--strip-components=1]
        creates: /usr/local/go-{{ golang }}/bin/go
  - name: "append golang to profile"
    lineinfile:
        path: /etc/profile.d/golang.sh
        line: 'export PATH=/usr/local/go-{{ golang }}/bin:$PATH'
        regexp: 'export PATH='
        create: yes
        state: present
  - name: Install dlv debugger
    shell:
      cmd: /usr/local/go-{{ golang }}/bin/go install github.com/go-delve/delve/cmd/dlv@latest

  - name: Install go language server
    shell:
      cmd: /usr/local/go-{{ golang }}/bin/go install golang.org/x/tools/gopls@latest
